version: '3.6'
services:
  app:
    container_name: 001.local.proxy
    image: shroomlife/shroomlife.de:latest
    restart: always
  proxy:
    container_name: proxy
    image: shroomlife/docker-https-proxy:latest
    ports:
      - "80:80"
      - "443:443"