version: '3.6'
services:
  app:
    container_name: shroomlife.de.local
    restart: always
    build: .
    networks:
      - default
    labels:
      guru.host: "shroomlife.de"
    volumes:
      - "node_modules_shroomlife_de:/app/node_modules"
volumes:
  node_modules_shroomlife_de:
networks:
  default:
    external:
      name: shroom001
